apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinerate-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinerate-api-gateway
  template:
    metadata:
      labels:
        app: cinerate-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: basith1519/cinerate-api-gateway:v1.0.2
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: cinerate-api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cinerate-api-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cinerate-api-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
