apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    service: user-service
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    
    # Create user database if it doesn't exist
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      SELECT 'CREATE DATABASE cinerate_user_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'cinerate_user_db')\gexec
    EOSQL
    
    # Connect to user database and create tables
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "cinerate_user_db" <<-EOSQL
      CREATE TABLE IF NOT EXISTS "Users" (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    EOSQL
